#!/usr/bin/perl
#
#    allpo is a program that loads all translations from .desktop and
#    .directory files into .po file format and stores them back.
#    that makes translating .desktop files a lot faster and cleaner...
#
#    Probably there are still bugs in the code and some parts could
#    be written much more efficenlty, but for now it is enough that
#    it works for me
#    feel free to send comments to andraz.tori1@guest.arnes.si
#    allpo (c) Andraz Tori 2000




	$action=$ARGV[0];
	$path=$ARGV[1];
	$lang=$ARGV[2];
	if (!$lang) {$lang="sl";};	
	$tmpfile="/tmp/tmp.po";

	%vse,%trans,%is;
	$c="\x23";
	@lines;
	
	

sub s_flushout {
	($s_name,$o,$t)=@_;
	my $ln=0;
	my $applied=0;
	my $change=0;
	foreach $line (@lines) {
		if ($line=~m/^(.*?)\[$lang]\=(.*)\n/) {
			my $name=$1;
			my $data=$2;
			if ($name eq $s_name) {
				$applied=1;
				if ($t ne $data) {
					$change=1;
#					if ($change) {print "a $t\n";};
				};
				$lines[$ln]=$s_name . "[$lang]=".$t."\n";
			}
		}
		$ln++;	
	}
	while ($ln=shift (@lines)) {
		print OUT $ln;


		if ($t) {
			if (!$applied) {
				if ($ln=~m/^$s_name\=(.*)/) {

					$change=1;
				print OUT $s_name . "[$lang]=".$t."\n";
				}
			}
		}

	}
#	if ($change) {print "a $t\n";}	

	return ($change);


}

sub s_fast_flushout {
	while ($ln=shift (@lines)) {
		print OUT $ln;
	}

	
}

sub store_trans {
	my $change=0;
	($filename,$s_section,$s_name,$o,$t)=@_;
	my $section,$newsection;
	open (OUT,">$tmpfile");
	open (FILE,"<$filename");


	while ($line=<FILE>) {
		if ($line=~m/^[ \t]*\[(.*)\][ \t]*$/) {
			my $newsection=$1;
			if ($section eq $s_section) {
				$change |= &s_flushout($s_name,$o,$t);	
			} else	{
				&s_fast_flushout();	
			}
			$section=$newsection;
		}
		push (@lines,$line);
	};

			if ($section eq $s_section) {
				$change |= &s_flushout($s_name,$o,$t);	
			} else	{
				&s_fast_flushout();	
			}

	close (FILE);
	close (OUT);
	if ($change) {
		print "Upd: $filename\n";
		system ("cp $tmpfile $filename"); 
#		system ("cat $tmpfile");
	}
}




#	print "$c _FILE $filename\n$c _SECT $section\n$c _NAME $name\nmsgid \"$o\"\nmsgstr \"$t\"\n\n";


sub l_print {
	($filename,$section,$name,$o,$t)=@_;
	print "$c _FILE $filename\n$c _SECT $section\n$c _NAME $name\nmsgid \"$o\"\nmsgstr \"$t\"\n\n";
}

sub l_flushout {
	my ($filename,$section)=@_;
	my $name;
	foreach $name (keys(%is)) {
		my $t=$trans{$name};
		my $o=$vse{$name};
		delete $is{$name};
		if ($o) {	# check if original is specified
			&l_print($filename,$section,$name,$o,$t);
		}
	}
	foreach $name (keys(%trans)) {
		delete $trans{$name};
	}
	foreach $name (keys(%vse)) {
		delete $vse{$name};
	}
}

sub load_f {
	my $filename=$_[0];
	my $section,$newsection;

	open (FILE,"<$filename");
	while ($line=<FILE>) {
		if ($line=~m/^[ \t]*\[(.*)\][ \t]*$/) {
			my $newsection=$1;
			&l_flushout($filename,$section);		
			$section=$newsection;		
		}
		if ($line=~m/^([^\[\]]*?)\=(.*)/) {
			my $name=$1;
			my $data=$2;
			$vse{$name}=$data;
		}	
		if ($line=~m/^(.*?)\[(\w*)]\=(.*)/) {
			my $name=$1;
			my $linelang=$2;
			my $data=$3;
			$is{$name}=1;
			if ($linelang eq $lang) {
				$trans{$name}=$data;
			}
		}
	};
	&l_flushout($filename,$section);

	close (FILE);
}


if ($action eq "load") {

	my $a;
	my $filename;	

	print "\n\n$c Automaticly generated by allpo\n";
	print "$c _LANG $lang\n\n";

	open(TMPFILE, "find $path -print|");
	while ($filename=<TMPFILE>) {	
		chop $filename;
		if ($filename=~m/~$/) {next;};
		if ($filename=~m/(\.desktop$)|(\.directory$)/) {
			&load_f ($filename);
		}
	}
	close(TMPFILE);
} elsif ($action eq "store") {
	my $filename,$section,$name,$msgid,$msgstr;	
	open(TMPFILE, "$path");
	while ($line=<TMPFILE>) {
		chop $line;
		if ($line=~m/^$c _LANG (.*)$/) {
			$lang=$1;
			print "Language set to $lang\n";
		} 

		if ($line=~m/^$c _FILE (.*)$/) {
			$filename=$1;
		} 

		if ($line=~m/^$c _SECT (.*)$/) {
			$section=$1;
		} 

		if ($line=~m/^$c _NAME (.*)$/) {
			$name=$1;
		} 

		if ($line=~m/^msgid \"(.*)\"$/) {
			$msgid=$1;
		} 
		if ($line=~m/^msgstr \"(.*)\"$/) {
			$msgstr=$1;
			store_trans($filename,$section,$name,$msgid,$msgstr);
		} 


	}
	close(TMPFILE);

} else {

print "allpo, automatically loads translations from .desktop files and
stores them back

Usage:
allpo load /directory lang
allpo store file.po

allpo (c) Andraz Tori 2000
"; 

}






