<html>

<head>
<title>
Projeto Brasileiro de Tradução do Gnome
</title>
</head>

<body bgcolor="white" background="bg-really-light.jpg">

<table>
<tr>
<td>
<a href="http://br.tldp.org/projetos/gnome/" border=0>
<img src="gnome-br-logo.png" border=0>
</a>
</td>
<td>
<h1>Projeto Brasileiro de Tradução do Gnome</h1>
</td>
</table>

<hr noshade>

<table cellspacing=6 cellpadding=6>
<tr>

<td valign="top">

<b>Menu</b>
<hr noshade>

<a href="http://br.tldp.org/">LDP-BR</a>
<p>
<a href="http://br.tldp.org/projetos/kde/">KDE-BR</a>
<p>
<a href="http://debian-br.cipsga.org.br">Debian-BR</a>
<p>
<a href="http://oobr.querencialivre.rs.gov.br">OpenOffice.org Brasil</a>

</td>

<td> <!-- principal! -->

