/* Automatically generated by po2tbl.sed from spellutils.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"only one -l option is allowed", 2},
  {"getopt returned impossible value: %d ('%c')", 3},
  {"\
Usage: pospell [-fsv] [-l language] -n pofile -p program\n\
       [-- [program-arguments...]]\n\
\n\
Copies all translated strings from `pofile' to a temporary\n\
file (the `spellfile') and then calls the program `program'\n\
(typically a spell checker) with all `program-arguments'.\n\
Afterwards the possibly changed translation is copied back\n\
into the `pofile'.\n\
\n\
If `pofile' is specified as `-', pospell will use its standard\n\
input and standard output.\n\
\n\
`%f' in the `program arguments' will be expanded to the name of\n\
the `spellfile'. Use `%%' for a real `%' character.\n\
\n\
The flags mean:\n\
 -f: The called program is a filter so don't make a temporary\n\
     file, but pipe `spellfile' to the standard input of the\n\
     `program' and later read it back from its standard output.\n\
 -l language: Only translations with the indicated language code\n\
     are copied to the `spellfile'.\n\
 -s: quit with an error message if the `pofile' or `spellfile'\n\
     have unrecognized formats.\n\
 -v: Print version and exit.\n", 4},
  {"%s died with signal \"%s\"", 5},
  {"%s died with signal no. %d", 6},
  {"child process couldn't execute %s", 7},
  {"%s returned failure exit code %d", 8},
  {"impossible status from child process: %x", 9},
  {"\
I don't understand this line in the .po file:\n\
%s", 10},
  {"\
found marker for a removed item in the spell file,\n\
but cannot find a corresponding item in the po file", 11},
  {"\
found line with unknown content in the spell file:\n\
%s", 12},
  {"\
Usage: newsbody [-fhqsv] [-k headername] -n message -p program\n\
       [-- [program-arguments...]]\n\
\n\
Copies the body of the e-mail or usenet message in `message'\n\
to a temporary file (the `bodyfile') and then calls the program\n\
`program' (e.g. a spell checker) with all `program-arguments'.\n\
Afterwards the possibly changed `bodyfile' is copied back into\n\
the `message'.\n\
\n\
If `message' is specified as `-', newsbody will use its\n\
standard input and standard output.\n\
\n\
`%f' in the `program arguments' will be expanded to the name of\n\
the `bodyfile'. Use `%%' for a real `%' character.\n\
\n\
The flags mean:\n\
 -f: The called program is a filter so don't make a temporary\n\
     file, but pipe `bodyfile' to the standard input of the\n\
     `program' and later read it back from its standard output.\n\
 -h: keep the entire header. This flag should also be used\n\
     if 'message' doesn't have a header at all.\n\
 -k headername: keep these header lines in the `bodyfile'.\n\
     (Multiple -k flags are allowed).\n\
 -q: Also remove quotes from the `bodyfile'.\n\
     Lines starting with `>' are considered quotes.\n\
 -s: Also remove signature from the `bodyfile'.\n\
     The signature is all lines from the first signature separator\n\
     (i.e. `-- ') to the bottom of the message.\n\
 -v: Print version and exit.\n", 13},
  {"\
found marker for a removed line in the body file,\n\
but cannot find a corresponding line in the message file", 14},
  {"internal error while reading a header continuation", 15},
  {"could not allocate memory", 16},
  {"reading file", 17},
  {"writing file", 18},
  {"open %s for reading", 19},
  {"open %s for writing", 20},
  {"closing file", 21},
  {"making temporary filename", 22},
  {"unlink %s", 23},
  {"rename %s %s", 24},
  {"stat %s", 25},
  {"read from %s", 26},
  {"write to %s", 27},
  {"error in child process", 28},
  {"error", 29},
  {", errno = %d", 30},
  {"fork", 31},
  {"open terminal read", 32},
  {"dup2 stdin", 33},
  {"close extra terminal read fd", 34},
  {"open terminal write", 35},
  {"dup2 stdout", 36},
  {"close extra terminal write fd", 37},
  {"exec %s", 38},
  {"pipe for output", 39},
  {"pipe for input", 40},
  {"close write end of output pipe", 41},
  {"close read end of output pipe", 42},
  {"close read end of input pipe", 43},
  {"close write end of input pipe", 44},
  {"fdopen write end of output pipe", 45},
  {"fdopen read end of input pipe", 46},
  {"waiting for child", 47},
};

int _msg_tbl_length = 47;
